name: fileshare
version: 1.1.9
summary: File Share
description: File Share

confinement: strict
base: core18
grade: stable

slots:
  dbus-fileshare: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.tripleafoodies.fileshare # adjust accordingly to your app name and

apps:
  fileshare:
    command: fileshare
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
      - home
      - network
    slots:
      - dbus-fileshare

build-packages:
  - libwebkit2gtk-4.0-dev
  - libsecret-1-dev
  - libjsoncpp-dev



parts:
  fileshare:
    stage-packages:
      - libjsoncpp1
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
  zenity-integration:
      plugin: nil
      stage-snaps:
      - zenity-integration